### ISSUE TITLE
Override of abstract classes

### ISSUE THREAD

**Issue by alainbernard** [opcoach/genModelAddon#13]
In the case of abstract superclasses, the classes hierarchy of the generated concrete implementations is not consistent.
Example: 
B extends A so EMF will generate MBImpl extends MAImpl
Genmodel addon will generate AImpl and BImpl extends MBImpl (extends MAImpl). So BImpl will not extend AImpl and will not inherit the code written manually in AImpl

**Comment by opcoach** [comment]
This issue is fixed now with the following process : 
- select dynamic templates in the genmodel
- set the templates directory to :  'yourProjectName'/templates in the genmodel
- generate the dev structure (it will create a specific Class.javajet files in the templates directory)
- generate again the model structure
- right click on the src-gen and organize imports.

This process will be simplified later (genmodel set automatically, imports well generated, ...) but it works now with this fix. I will deliver a new update site...

**Comment by opcoach** [comment]
Version is now 1.1.0
