### ISSUE TITLE
Generation Pb with interfaces

### ISSUE THREAD

**Issue by st20085** [opcoach/genModelAddon#62]
Salut Olivier

[In French]
Voici un plugin contenant un modèle Ecore simplifié ou il y a juste une classe Next (c’est juste pour te montrer) et les sources générées.
J’ai un pb avec la classe MNextImpl ds src-gen. 

J’ai voulu me rajouter une méthode dans la classe Next mais j’ai une exception (méthode non définie ds l’implémentation) ds la classe MNextImpl alors que cela aurait du être dans la classe NextImpl.

Comme tu peux le voir la classe MNextImpl générée est définie comme ça
public class MNextImpl extends MinimalEObjectImpl.Container implements Next {

mais je pense que la génération de la classe n’est pas bonne mais doit plutôt implémenter l’interface du modèle.
public class MNextImpl extends MinimalEObjectImpl.Container implements **MNext** {

_Alain pense lui aussi que c'est un bug_
[/In French]

[bug.on.genmodeladdon2.zip](https://github.com/opcoach/genModelAddon/files/591950/bug.on.genmodeladdon2.zip)

**Comment by opcoach** [comment]
Salut Cyril,

Sorry to answer in english, but for the project's history it is better. 

Actually this issue is not a bug and the code is correctly generated. 

If you have 2 EClasses in your model, for instance Project and DocumentProject extending Project, we must be sure that the MDocumentProjectImpl extends the ProjectImpl class in case a new method (for instance 'compare') has been added in the Project interface. 

If we do not generate like this, we will have to implement twice the 'compare' method : in ProjectImpl and in DocumentationProjectImpl and it will not be good. 

So, for this example we must definitively have : 

   DocumentProjectImpl -> MDocumentProjectIMpl -> ProjectImpl -> MProjectImpl
and
  DocumentProject -> MDocumentProject -> Project -> MProject

As you can see the generated and developper code are mixed..  

It can be tricky to explain but there is no other solution... 

May be if we don't want to force to have a default implementation in the interface, we could try to generate an 'abstract' class for all M*Impl generated classes (and I will have to change the factory generated code, because the 'abstract' property will not be set in the model)... 

I let the bug opened for the discussion.. and to get your feedback. 

Thank you
