### ISSUE TITLE
EMF model code generation should use GMA generation if the project is managed by GMA

### ISSUE THREAD

**Issue by opcoach** [opcoach/genModelAddon#89]
In a workspace several projects may be defined... some of them with standard EMF generation and others with GMA feature. 

The EMF model code generation is overridden by GMA, regarding the naming of some classes.  This should be done only if the project has a specific GMA nature.

**Comment by PhilippeNoel** [comment]
Olivier,
My comments... _**below prefixed with PNO**:_

...
This is a good idea to have this nature on the project. It is important to distinguish the code generation depending on the project (need GMA generation or not).

Have you seen that the GenModelFactory is overridden by the genModelAddon.core plugin ? It means that all objects created when reading the genmodel file are created by this factory. The reason is to simplify the way to compute the class names by the default EMF generator and to avoid to change any code in the default EMF generator !
_**PNO: Yes, I got this**_

Inside GMAGenXXXX instances, some methods are overridden to call the GMATransform.replaceDevName static method. (see the end of file : https://github.com/opcoach/genModelAddon/blob/master/com.opcoach.genmodeladdon.core/src/com/opcoach/genmodeladdon/core/genmodel/GMATransform.xtend)

May be this method should transform the names not only if this is a GMAGenModel instance but also if this model is inside a GMA nature project ?

**_PNO: I think that it is what I proposed in the code_**

What will happen if we select/unselect the GMA nature if the genModel objects instances are already created, and the we regenerate the EMF model code layer ? Have you tested it ?
**_PNO: I've tested creating two GMA projects, I generate all needed code for both of them, then disable the GMA nature for the second one. I've also created two non-GMA projects, with generation of code then ensable the GMA nature for the second one.
Then I compared the results.
There are more thinks to do when disabling a GMA nature on a previously GMA project, because the structure is different (one must remove the src folder and probably adapt the genmodel file too. We can even remove the 'disable GMA nature option'?
For the reverse case (enabling GMA nature on a previously created project): This is seamless, as it is already managed by GMA plugin when creating the structure..._**

Did you also consider that a '.gma' file is created in the root directory of the project ? It contains the properties setup from the GMA dialog so as to restore it. Wouldn't be enough to know that it is a GMA project ?
**_PNO: IMO this wouldn't be enough, because '.gma' file is only created if we use the 'generate developer structure' command. We can not use it to know if we must show the menu showing the 'generate developer structure'._**

And to finish, depending on the GMA project nature, the 'Generate Dev Structure' in the menu should be displayed or not. So should we let the menu always displayed and switch the nature automatically, or should we first switch the nature, and then access to the menu ?
**_PNO: see above remark_**

I opened a new issue to track your work : #89

I also accepted the Actions on the GitHub project for your contribution. It seems that a push in your fork should be automatically compiled on your side (so as to check if all the tests are passed).

**_PNO: concerning the tests, I don't know yet how to assign the GMA nature to the projects created during the tests. I'm looking at it today_**

Discussion is opened :)
**_PNO: Yes I see :-) Thanks for that_**

**Comment by PhilippeNoel** [comment]
Tests are now all PASSED
What do you think about suppressing the option to remove the GMA nature ?

**Comment by opcoach** [comment]
Hi Philippe, 

I tested your PR and everything is OK for me. The only 'big change' is that now, an EMF project should be configured as a GMA Nature project to get the action menu 'Generate Developer structure' .. but this is not a problem. I should mention it in the documentation. 

For disabling GMA nature I think it is ok like it is...  Of course, if this is generated with GMA there will be 2 source codes, and the relation ship between objects is different than if code is only generated by EMF model layer. Namely for the case of : A is a superclass of B :  with standard EMF it will generate B extends A, but with GMA it will generate :  MA <- A <- MB <- B  (with <- meaning extends). 

So I would suggest that if the developper switch the nature, he has to regenerate properly using 'generate model code'  and remove the src generated code. 

I tried it with your PR, and this works well. 

May be it would be interesting to add tests to ensure that only EMF code generation is called when GMA nature is unset. But it is fine for me. 

For these reasons I will merge directly your PR.
