### ISSUE TITLE
Cancellation message in override dialog is not clear

### ISSUE THREAD

**Issue by alainbernard** [opcoach/genModelAddon#9]
When selecting the files to be overriden and clicking on Cancel, a message indicates that the files have been generated. From a user point of view, when clicking on Cancel, we expect that the whole generation process is canceled, regardless of the need to override files or not.

**Comment by opcoach** [comment]
Ok. Now a first blank generation is launched to check if some files will be overridden. Two cases : 
- No file will be overriden : the new files are generated and the destination directory is displayed. 
- Some files will be overridden : the file selection dialog is displayed. If it is canceled nothing is generated, and if not, the selected files and the new files are generated. Then the dialog displays the destination directory.

Fixed with 534787b1b82af75f4feb0485276bf7d519999b9d
